apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw4-web
  labels:
    app: hw4-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw4-web
  template:
    metadata:
      labels:
        app: hw4-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hw4-web
          image: cr.yandex/crp5r2ea62v097ks2o4n/hw4-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: NUM_ARTICLES_TRAIN
              value: "1000"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: FLOWER_UNAUTHENTICATED_API
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15