apiVersion: batch/v1
kind: Job
metadata:
  name: hw4-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: migrate
          image: cr.yandex/crp5r2ea62v097ks2o4n/hw4-app:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: NUM_ARTICLES_TRAIN
              value: "1000"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: FLOWER_UNAUTHENTICATED_API
              value: "true"
  backoffLimit: 2